# Generated by Django 5.2.5 on 2025-08-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('founded_year', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kit_type', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('third', 'Third'), ('special', 'Special'), ('training', 'Training'), ('keeper', 'Keeper')], max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.team')),
            ],
        ),
    ]
